# Generated by Django 5.0.14 on 2025-06-29 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enlaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enlace',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='enlaces/'),
        ),
    ]
