# Generated by Django 5.0.14 on 2025-07-08 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reuniones', '0002_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En Progreso'), ('FINALIZADO', 'Finalizado')], default='PENDIENTE', max_length=20),
        ),
    ]
