# Generated by Django 5.0.14 on 2025-07-08 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reuniones', '0003_evento_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='cargo',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='firma',
            field=models.ImageField(blank=True, null=True, upload_to='reuniones/', verbose_name='Firma'),
        ),
    ]
