# Generated by Django 5.0.14 on 2025-07-08 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reuniones', '0004_persona_cargo_persona_firma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='dni',
            field=models.CharField(max_length=50, verbose_name='DNI'),
        ),
    ]
