# Generated by Django 5.0.14 on 2025-07-07 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='newsletter',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen destacada del boletín', null=True, upload_to='newsletters/img/'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletters', to=settings.AUTH_USER_MODEL),
        ),
    ]
