# Generated by Django 5.0.14 on 2025-07-08 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0002_alter_newsletter_options_newsletter_imagen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text='Imagen del boletín', upload_to='newsletters/img/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='boletin.newsletter')),
            ],
            options={
                'ordering': ['orden', 'created_at'],
            },
        ),
    ]
