# Generated by Django 5.0.14 on 2025-07-08 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0003_newsletterimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='imagen',
        ),
    ]
