# Generated by Django 5.0.14 on 2025-07-08 15:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0004_remove_newsletter_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletterimage',
            options={'ordering': ['orden', 'created_at'], 'verbose_name': 'Imagen de boletín', 'verbose_name_plural': 'Imágenes de boletines'},
        ),
        migrations.AddField(
            model_name='newsletterimage',
            name='es_portada',
            field=models.BooleanField(default=False, help_text='¿Es la imagen principal/portada del boletín?'),
        ),
        migrations.AddField(
            model_name='newsletterimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='newsletterimage',
            name='imagen',
            field=models.ImageField(help_text='Imagen del boletín (formatos: JPG, PNG, GIF)', upload_to='newsletters/img/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='newsletterimage',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Orden de visualización (0=primero)'),
        ),
        migrations.AddConstraint(
            model_name='newsletterimage',
            constraint=models.UniqueConstraint(condition=models.Q(('es_portada', True)), fields=('newsletter', 'es_portada'), name='unique_portada_por_newsletter'),
        ),
    ]
