# Generated by Django 5.0.14 on 2025-07-07 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_password_reset_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Directorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Nombre')),
                ('tipo', models.CharField(max_length=500, verbose_name='Tipo')),
            ],
        ),
    ]
