# Generated by Django 5.0.14 on 2025-07-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_directorio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=8, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('distrito', models.CharField(max_length=100)),
                ('disa', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=20)),
            ],
        ),
    ]
