# Generated by Django 5.0.14 on 2025-07-16 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_establecimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilEstablecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_usuario_establecimiento', models.BooleanField(default=True)),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.establecimiento')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_establecimiento', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('acceso_modulo1', 'Puede acceder al módulo 1'), ('acceso_modulo2', 'Puede acceder al módulo 2')],
            },
        ),
    ]
