# Generated by Django 5.0.14 on 2025-07-16 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_perfilestablecimiento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilestablecimiento',
            options={'permissions': [('acceso_consulta_externa', 'Puede acceder al módulo de consulta externa'), ('acceso_modulo2', 'Puede acceder al módulo 2')]},
        ),
        migrations.CreateModel(
            name='ConsultaExterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_seguro', models.CharField(choices=[('SIS', 'Seguro Integral de Salud'), ('ESSALUD', 'ESSALUD'), ('PRIVADO', 'Seguro Privado'), ('OTRO', 'Otro')], max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('lugar_procedencia', models.CharField(max_length=100)),
                ('tipo_documento', models.CharField(choices=[('DNI', 'Documento Nacional de Identidad'), ('CE', 'Carnet de Extranjería'), ('PASAPORTE', 'Pasaporte')], max_length=10)),
                ('documento', models.CharField(max_length=20)),
                ('n_hcl', models.CharField(max_length=20, verbose_name='Número de Historia Clínica')),
                ('fecha_hora_cita_otorgada', models.DateTimeField()),
                ('fecha_hora_atencion', models.DateTimeField()),
                ('diagnostico_medico', models.TextField()),
                ('dx_CIE_10_1', models.CharField(max_length=10, verbose_name='Diagnóstico CIE-10 Principal')),
                ('dx_CIE_10_2', models.CharField(blank=True, max_length=10, null=True, verbose_name='Diagnóstico CIE-10 Secundario')),
                ('dx_CIE_10_3', models.CharField(blank=True, max_length=10, null=True, verbose_name='Diagnóstico CIE-10 Terciario')),
                ('especialidad', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_hora_atencion'],
                'permissions': [('puede_ver_consulta_externa', 'Puede ver registros de consulta externa'), ('puede_crear_consulta_externa', 'Puede crear registros de consulta externa'), ('puede_editar_consulta_externa', 'Puede editar registros de consulta externa')],
            },
        ),
    ]
