# Generated by Django 5.0.14 on 2025-07-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_perfilestablecimiento_options_consultaexterna'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilestablecimiento',
            name='establecimiento',
        ),
        migrations.RemoveField(
            model_name='perfilestablecimiento',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='consultaexterna',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='access_ConsultaExterna',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='categoria',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='codigo',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='disa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='distrito',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Establecimiento',
        ),
        migrations.DeleteModel(
            name='PerfilEstablecimiento',
        ),
    ]
