# Generated by Django 5.0.14 on 2025-07-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_user_access_consultaexterna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultaexterna',
            name='tipo_seguro',
            field=models.CharField(max_length=70),
        ),
    ]
