# Generated by Django 5.0.14 on 2025-07-16 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_consultaexterna_tipo_documento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultaexterna',
            old_name='genero',
            new_name='sexo',
        ),
    ]
