# Generated by Django 5.0.14 on 2025-07-30 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_rename_genero_consultaexterna_sexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cirugia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_seguro', models.CharField(max_length=70)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('lugar_procedencia', models.CharField(max_length=100)),
                ('n_hcl', models.CharField(max_length=20, verbose_name='Número de Historia Clínica')),
                ('fecha_iqx_programada', models.DateTimeField()),
                ('codigo_iqx_programada', models.CharField(max_length=100)),
                ('iqx_programada', models.CharField(max_length=100)),
                ('fecha_iqx_realizada', models.DateTimeField()),
                ('codigo_iqx_realizada', models.CharField(max_length=100)),
                ('iqx_realizada', models.CharField(max_length=100)),
                ('se_reprogramo', models.CharField(max_length=100)),
                ('fecha_iqx_reprogramada', models.DateTimeField()),
                ('motivo_reprogramacion', models.DateTimeField()),
                ('fecha_realizada_iqx_reprogramada', models.DateTimeField()),
                ('codigo_iqx_reprogramada', models.CharField(max_length=100)),
                ('iqx_reprogramada', models.CharField(max_length=100)),
            ],
        ),
    ]
