# Generated by Django 5.0.14 on 2025-07-30 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_cirugia_fecha_actualizacion_cirugia_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cirugia',
            name='creado_por',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='cirugias', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
