# Generated by Django 5.0.14 on 2025-07-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_cirugia_creado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cirugia',
            name='motivo_reprogramacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
