# Generated by Django 5.0.14 on 2025-07-30 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_cirugia_motivo_reprogramacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultaexterna',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='consultaexterna',
            name='tipo_documento',
        ),
    ]
