# Generated by Django 5.0.14 on 2025-06-14 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Nombre')),
                ('tipo', models.CharField(max_length=500, verbose_name='Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('EESS', 'Establecimiento de Salud'), ('DIRIS', 'Dirección de Red Integrada de Salud'), ('DIRESA', 'Dirección Regional de Salud'), ('GERESA', 'Gerencia Regional de Salud')], max_length=10)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('categoria', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('nombre_proceso', models.CharField(max_length=200)),
                ('dueño_proceso', models.CharField(max_length=200)),
                ('objetivo', models.TextField()),
                ('objetivo_estrategico', models.TextField()),
                ('prov_entrada', models.TextField()),
                ('elemento_entrada', models.TextField()),
                ('actividad_proceso', models.TextField()),
                ('riesgos', models.TextField()),
                ('registros', models.TextField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procesos', to='ficha.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Subproceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('1', 'Nivel 1'), ('2', 'Nivel 2'), ('3', 'Nivel 3')], default='1', max_length=1)),
                ('nombre', models.TextField(blank=True, null=True)),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subprocesos', to='ficha.proceso')),
            ],
            options={
                'ordering': ['proceso'],
            },
        ),
        migrations.CreateModel(
            name='Verificador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('orden', models.PositiveIntegerField(default=0)),
                ('estado', models.CharField(blank=True, choices=[('SI', ' SI CUMPLE'), ('NO', ' NO CUMPLE'), ('NA', ' NO APLICA')], max_length=2, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('subproceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verificadores', to='ficha.subproceso')),
            ],
            options={
                'verbose_name_plural': 'Verificadores',
                'ordering': ['orden'],
            },
        ),
    ]
