# Generated by Django 5.0.14 on 2025-06-14 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificador',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='verificador',
            name='observaciones',
        ),
    ]
