# Generated by Django 5.0.14 on 2025-06-08 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(default=2, max_length=500, verbose_name='Tipo'),
            preserve_default=False,
        ),
    ]
