# Generated by Django 5.0.14 on 2025-06-09 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0002_categoria_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=200)),
                ('nombre_proceso', models.CharField(max_length=200)),
                ('dueño_proceso', models.CharField(max_length=200)),
                ('objetivo', models.TextField()),
                ('objetivo_estrategico', models.TextField()),
                ('prov_entrada', models.TextField()),
                ('elemento_entrada', models.TextField()),
                ('actividad_proceso', models.TextField()),
                ('riesgos', models.TextField()),
                ('registros', models.TextField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procesos', to='ficha.categoria')),
            ],
        ),
    ]
