# Generated by Django 5.0.14 on 2025-06-16 03:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0002_remove_verificador_estado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionVerificador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('C', 'Cumple'), ('NC', 'No Cumple'), ('NA', 'No Aplica')], max_length=2)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_evaluacion', models.DateTimeField(auto_now_add=True)),
                ('establecimiento', models.CharField(max_length=200, verbose_name='Nombre de la IPRESS')),
                ('tipo', models.CharField(choices=[('EESS', 'Establecimiento de Salud'), ('DIRIS', 'Dirección de Red Integrada de Salud'), ('DIRESA', 'Dirección Regional de Salud'), ('GERESA', 'Gerencia Regional de Salud')], max_length=10, verbose_name='Tipo de IPRESS')),
                ('codigo', models.CharField(max_length=20, verbose_name='Código de la IPRESS')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoría')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('verificador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='ficha.verificador')),
            ],
            options={
                'verbose_name_plural': 'Evaluaciones',
                'ordering': ['-fecha_evaluacion'],
            },
        ),
        migrations.DeleteModel(
            name='Institucion',
        ),
    ]
