# Generated by Django 5.0.14 on 2025-06-09 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0003_proceso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proceso',
            name='titulo',
        ),
    ]
