# Generated by Django 5.0.14 on 2025-06-17 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0003_evaluacionverificador_delete_institucion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluacionverificador',
            name='observaciones',
        ),
    ]
