# Generated by Django 5.0.14 on 2025-06-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0004_remove_evaluacionverificador_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceso',
            name='tiutlo',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
