# Generated by Django 5.0.14 on 2025-06-14 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0004_remove_proceso_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subproceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, verbose_name='Código (ej. PE1.1)')),
                ('nombre', models.CharField(max_length=500)),
                ('nivel', models.CharField(choices=[('1', 'Nivel 1'), ('2', 'Nivel 2'), ('3', 'Nivel 3')], default='1', max_length=1)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subprocesos', to='ficha.proceso')),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
    ]
