# Generated by Django 5.0.14 on 2025-06-17 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0005_proceso_tiutlo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proceso',
            old_name='tiutlo',
            new_name='titulo',
        ),
    ]
