# Generated by Django 5.0.14 on 2025-06-14 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0005_subproceso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subproceso',
            options={'ordering': ['proceso']},
        ),
        migrations.RemoveField(
            model_name='subproceso',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='subproceso',
            name='nombre',
        ),
    ]
