# Generated by Django 5.0.14 on 2025-06-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0006_alter_subproceso_options_remove_subproceso_codigo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('EESS', 'Establecimiento de Salud'), ('DIRIS', 'Dirección de Red Integrada de Salud'), ('DIRESA', 'Dirección Regional de Salud'), ('GERESA', 'Gerencia Regional de Salud')], max_length=10)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('Categoria', models.CharField(max_length=200)),
            ],
        ),
    ]
