# Generated by Django 5.0.14 on 2025-06-18 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0006_rename_tiutlo_proceso_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatrizCompromiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_situacional', models.TextField(verbose_name='Descripción del estado situacional')),
                ('semaforo', models.CharField(max_length=50, verbose_name='Semáforo')),
                ('riesgo_identificado', models.TextField(verbose_name='Identificación del Riesgo')),
                ('medidas_correctivas', models.TextField(verbose_name='Medidas correctivas/Compromisos')),
                ('hito_esperado', models.TextField(verbose_name='Hito esperado')),
                ('responsable_directo', models.CharField(max_length=200, verbose_name='Responsable directo (A)')),
                ('plazo_inicio', models.DateField()),
                ('plazo_fin', models.DateField()),
                ('funcionario_depen_directo', models.CharField(max_length=200, verbose_name='Funcionario (B)')),
                ('funcionario_depen_indirecto', models.CharField(max_length=200, verbose_name='Funcionario (C)')),
                ('firmas_adicionales', models.TextField(blank=True, verbose_name='Firmas adicionales (máx. 5)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matrices', to='ficha.evaluacionverificador')),
            ],
            options={
                'verbose_name': 'Matriz de Compromiso',
                'verbose_name_plural': 'Matrices de Compromiso',
            },
        ),
    ]
