# Generated by Django 5.0.14 on 2025-06-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0007_matrizcompromiso'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrizcompromiso',
            name='evaluaciones_nc',
            field=models.ManyToManyField(related_name='matrices_asociadas', to='ficha.evaluacionverificador', verbose_name='Evaluaciones No Conformes'),
        ),
    ]
