# Generated by Django 5.0.14 on 2025-06-14 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0007_institucion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='subproceso',
            old_name='descripcion',
            new_name='nombre',
        ),
        migrations.CreateModel(
            name='FichaVerificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ficha.institucion')),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ficha.proceso')),
            ],
            options={
                'verbose_name': 'Ficha Técnica de Monitoreo',
                'verbose_name_plural': 'Fichas Técnicas de Monitoreo',
            },
        ),
        migrations.CreateModel(
            name='Verificador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('orden', models.PositiveIntegerField(default=0)),
                ('subproceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verificadores', to='ficha.subproceso')),
            ],
            options={
                'verbose_name_plural': 'Verificadores',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoVerificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(blank=True, choices=[('SI', 'SI CUMPLE'), ('NO', 'NO CUMPLE'), ('NA', 'NO APLICA')], max_length=2, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='ficha.fichaverificacion')),
                ('verificador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ficha.verificador')),
            ],
            options={
                'verbose_name': 'Resultado de Verificación',
                'verbose_name_plural': 'Resultados de Verificación',
                'unique_together': {('ficha', 'verificador')},
            },
        ),
    ]
