# Generated by Django 5.0.14 on 2025-06-19 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0008_matrizcompromiso_evaluaciones_nc'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrizcompromiso',
            name='funcionario_d',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Funcionario (D)'),
        ),
        migrations.AddField(
            model_name='matrizcompromiso',
            name='funcionario_eo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Funcionario (E)'),
        ),
    ]
