# Generated by Django 5.0.14 on 2025-06-19 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0010_rename_funcionario_eo_matrizcompromiso_funcionario_e'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrizcompromiso',
            name='firma_a',
            field=models.ImageField(blank=True, null=True, upload_to='firmas_matrices/', verbose_name='Firma Responsable Directo (A)'),
        ),
        migrations.AddField(
            model_name='matrizcompromiso',
            name='firma_b',
            field=models.ImageField(blank=True, null=True, upload_to='firmas_matrices/', verbose_name='Firma Funcionario (B)'),
        ),
        migrations.AddField(
            model_name='matrizcompromiso',
            name='firma_c',
            field=models.ImageField(blank=True, null=True, upload_to='firmas_matrices/', verbose_name='Firma Funcionario (C)'),
        ),
        migrations.AddField(
            model_name='matrizcompromiso',
            name='firma_d',
            field=models.ImageField(blank=True, null=True, upload_to='firmas_matrices/', verbose_name='Firma Funcionario (D)'),
        ),
        migrations.AddField(
            model_name='matrizcompromiso',
            name='firma_e',
            field=models.ImageField(blank=True, null=True, upload_to='firmas_matrices/', verbose_name='Firma Funcionario (E)'),
        ),
    ]
