# Generated by Django 5.0.14 on 2025-06-23 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0011_matrizcompromiso_firma_a_matrizcompromiso_firma_b_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacionverificador',
            name='departamento',
            field=models.CharField(default=2, max_length=100, verbose_name='Departamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluacionverificador',
            name='disa',
            field=models.CharField(default=2, max_length=100, verbose_name='Disa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluacionverificador',
            name='distrito',
            field=models.CharField(default=2, max_length=100, verbose_name='Distrito'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluacionverificador',
            name='provincia',
            field=models.CharField(default=2, max_length=100, verbose_name='Provincia'),
            preserve_default=False,
        ),
    ]
