# Generated by Django 5.0.14 on 2025-06-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0012_evaluacionverificador_departamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacionverificador',
            name='departamento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='evaluacionverificador',
            name='disa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='DISA'),
        ),
        migrations.AlterField(
            model_name='evaluacionverificador',
            name='distrito',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Distrito'),
        ),
        migrations.AlterField(
            model_name='evaluacionverificador',
            name='provincia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Provincia'),
        ),
    ]
