# Generated by Django 5.0.14 on 2025-06-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0013_alter_evaluacionverificador_departamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacionverificador',
            name='institucion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Institucion'),
        ),
    ]
