# Generated by Django 5.0.14 on 2025-06-24 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0014_evaluacionverificador_institucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrizcompromiso',
            name='firma_m',
            field=models.ImageField(blank=True, null=True, upload_to='firmas_matrices/', verbose_name='Firma Monitor  (M)'),
        ),
    ]
