# Generated by Django 5.0.14 on 2025-06-25 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0015_matrizcompromiso_firma_m'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoMatrizCompromiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_seguimiento', models.DateField(verbose_name='Fecha de seguimiento')),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('EP', 'En Progreso'), ('C', 'Completado'), ('A', 'Aprobado'), ('R', 'Rechazado')], default='P', max_length=2, verbose_name='Estado del seguimiento')),
                ('analisis_accion', models.TextField(verbose_name='Análisis/Acción realizada')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('matriz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='ficha.matrizcompromiso')),
            ],
            options={
                'verbose_name': 'Seguimiento de Matriz de Compromiso',
                'verbose_name_plural': 'Seguimientos de Matrices de Compromiso',
                'ordering': ['-fecha_seguimiento', 'matriz'],
            },
        ),
    ]
