# Generated by Django 5.0.14 on 2025-06-25 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0016_seguimientomatrizcompromiso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimientomatrizcompromiso',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimientos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que registró'),
        ),
    ]
