# Generated by Django 5.0.14 on 2025-06-30 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0019_alertas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alertas',
        ),
    ]
