# Generated by Django 5.0.14 on 2025-06-30 00:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0021_alertas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertas',
            name='codigo',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=50, unique=True, verbose_name='Código'),
        ),
        migrations.CreateModel(
            name='SeguimientoAlertas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_seguimiento', models.DateField(verbose_name='Fecha de seguimiento')),
                ('estado', models.TextField(verbose_name='Estado')),
                ('analisis_accion', models.TextField(verbose_name='Análisis/Acción realizada')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('alertas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='ficha.alertas')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimientos_alertas_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que registró')),
            ],
        ),
    ]
