# Generated by Django 5.0.14 on 2025-06-30 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0022_alter_alertas_codigo_seguimientoalertas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seguimientoalertas',
            old_name='alertas',
            new_name='alerta',
        ),
    ]
