# Generated by Django 5.0.14 on 2025-06-30 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0023_rename_alertas_seguimientoalertas_alerta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimientoalertas',
            name='fecha_seguimiento',
            field=models.DateTimeField(verbose_name='Fecha y hora de seguimiento'),
        ),
    ]
