# Generated by Django 5.0.14 on 2025-06-30 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0024_alter_seguimientoalertas_fecha_seguimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimientoalertas',
            name='dias_personalizados',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Días para recordatorio personalizado'),
        ),
        migrations.AddField(
            model_name='seguimientoalertas',
            name='enviar_notificacion',
            field=models.BooleanField(default=True, verbose_name='Enviar notificación'),
        ),
        migrations.AddField(
            model_name='seguimientoalertas',
            name='frecuencia_envio',
            field=models.CharField(blank=True, choices=[('diario', 'Diario'), ('2dias', 'Cada 2 días'), ('3dias', 'Cada 3 días'), ('semanal', 'Semanal'), ('mensual', 'Mensual'), ('personalizado', 'Personalizado')], max_length=20, null=True, verbose_name='Frecuencia de recordatorio'),
        ),
        migrations.AddField(
            model_name='seguimientoalertas',
            name='proximo_envio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Próximo envío programado'),
        ),
    ]
