# Generated by Django 5.0.14 on 2025-06-30 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0025_seguimientoalertas_dias_personalizados_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seguimientoalertas',
            options={'ordering': ['-fecha_seguimiento'], 'verbose_name': 'Seguimiento de Alerta', 'verbose_name_plural': 'Seguimientos de Alertas'},
        ),
        migrations.AddField(
            model_name='alertas',
            name='hora_envio',
            field=models.TimeField(blank=True, help_text='Hora a la que se enviarán los recordatorios', null=True, verbose_name='Hora de envío programada'),
        ),
        migrations.AddField(
            model_name='seguimientoalertas',
            name='enviar_ahora',
            field=models.BooleanField(default=False, help_text='Marcar para enviar notificación inmediatamente al guardar', verbose_name='Enviar notificación inmediata'),
        ),
        migrations.AddField(
            model_name='seguimientoalertas',
            name='hora_envio',
            field=models.TimeField(blank=True, help_text='Hora específica para enviar los recordatorios (formato HH:MM)', null=True, verbose_name='Hora de envío programada'),
        ),
        migrations.AlterField(
            model_name='seguimientoalertas',
            name='alerta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='ficha.alertas', verbose_name='Alerta relacionada'),
        ),
        migrations.AlterField(
            model_name='seguimientoalertas',
            name='analisis_accion',
            field=models.TextField(help_text='Descripción detallada del análisis y acciones tomadas', verbose_name='Análisis/Acción realizada'),
        ),
        migrations.AlterField(
            model_name='seguimientoalertas',
            name='dias_personalizados',
            field=models.PositiveIntegerField(blank=True, help_text='Número de días para recordatorios personalizados', null=True, verbose_name='Días para recordatorio personalizado'),
        ),
        migrations.AlterField(
            model_name='seguimientoalertas',
            name='enviar_notificacion',
            field=models.BooleanField(default=True, help_text='Activar para enviar notificaciones automáticas', verbose_name='Enviar notificación'),
        ),
        migrations.AlterField(
            model_name='seguimientoalertas',
            name='estado',
            field=models.CharField(choices=[('P', 'Pendiente'), ('EP', 'En Progreso'), ('C', 'Completado'), ('A', 'Aprobado'), ('R', 'Rechazado')], default='P', max_length=2, verbose_name='Estado del seguimiento'),
        ),
        migrations.AlterField(
            model_name='seguimientoalertas',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de última actualización'),
        ),
        migrations.AlterField(
            model_name='seguimientoalertas',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='seguimientoalertas',
            name='fecha_seguimiento',
            field=models.DateTimeField(help_text='Fecha y hora en que se realizó el seguimiento', verbose_name='Fecha y hora de seguimiento'),
        ),
        migrations.AlterField(
            model_name='seguimientoalertas',
            name='frecuencia_envio',
            field=models.CharField(blank=True, choices=[('diario', 'Diario'), ('2dias', 'Cada 2 días'), ('3dias', 'Cada 3 días'), ('semanal', 'Semanal'), ('mensual', 'Mensual'), ('personalizado', 'Personalizado')], help_text='Frecuencia con la que se enviarán recordatorios', max_length=20, null=True, verbose_name='Frecuencia de recordatorio'),
        ),
        migrations.AlterField(
            model_name='seguimientoalertas',
            name='proximo_envio',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora del próximo recordatorio automático', null=True, verbose_name='Próximo envío programado'),
        ),
        migrations.AddIndex(
            model_name='seguimientoalertas',
            index=models.Index(fields=['proximo_envio'], name='ficha_segui_proximo_1fed7c_idx'),
        ),
        migrations.AddIndex(
            model_name='seguimientoalertas',
            index=models.Index(fields=['alerta'], name='ficha_segui_alerta__1763bd_idx'),
        ),
        migrations.AddIndex(
            model_name='seguimientoalertas',
            index=models.Index(fields=['usuario_creacion'], name='ficha_segui_usuario_a72347_idx'),
        ),
    ]
