# Generated by Django 5.0.14 on 2025-06-30 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0026_alter_seguimientoalertas_options_alertas_hora_envio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimientoalertas',
            name='frecuencia_envio',
            field=models.CharField(blank=True, choices=[('hoy', 'Hoy mismo'), ('diario', 'Diario'), ('2dias', 'Cada 2 días'), ('3dias', 'Cada 3 días'), ('semanal', 'Semanal'), ('mensual', 'Mensual'), ('personalizado', 'Personalizado')], help_text='Frecuencia con la que se enviarán recordatorios', max_length=20, null=True, verbose_name='Frecuencia de recordatorio'),
        ),
    ]
